version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main_2}"
    image: localstack/localstack:latest
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=kinesis,dynamodb,cloudformation,s3,sts,lambda,logs,iam
      - DEBUG=1
      - BUCKET_MARKER_LOCAL=localbucket
      - LAMBDA_REMOTE_DOCKER=1
      #- PORT_WEB_UI=8080

