service: myService

plugins:
  - serverless-plugin-typescript
  - serverless-scriptable-plugin
  - serverless-offline
  - serverless-localstack

custom:
  localstack:
    stages:
      # list of stages for which the plugin should be enabled
      - local
      - dev
    host: http://localhost  # optional - LocalStack host to connect to
    edgePort: 4566  # optional - LocalStack edge port to connect to
    autostart: true  # optional - Start LocalStack in Docker on Serverless deploy
    lambda:
      # Enable this flag to improve performance
      mountCode: True
    docker:
      # Enable this flag to run "docker ..." commands as sudo
      sudo: False
  scriptHooks:
    # These are all the places that jetpack could be invoked that would
    # ensure the TS files are built right before jetpack kicks in.
    #
    # Workaround for https://github.com/prisma-labs/serverless-plugin-typescript/issues/175
    before:package:createDeploymentArtifacts: yarn run build-ts-files
    before:package:function:package: yarn run build-ts-files
    before:jetpack:package:package: yarn run build-ts-files

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev # default stage
  lambdaHashingVersion: 20201221
  region: us-east-1
  environment:
    NODE_ENV: dev

useDotenv: true

package:
  exclude:
    - config/.env.stg
    - config/.env.pro
  include:
    - config/.env.dev

functions:
  hello:
    handler: app/handler.hello
  consumer:
    handler: app/handler.consumer
  producer:
    handler: app/handler.producer
